sudo: required

language: java

services:
- docker

before_install:
- docker build -t sepsyk/reverse ./reverseDockerfile/
- docker run -p 127.0.0.1:8081:8081 --name=reverse -d sepsyk/reverse
- docker build -t sepsyk/rand .
- docker run -p 8080:8080 --name=rand --link=reverse:reverse -d sepsyk/rand

script:
- ./smoketest.sh
- ./smoketest2.sh
